server:
  port: 8000

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
        - id: lecture-service
          uri: lb://LECTURE-SERVICE
          predicates:
            - Path=/lecture-service/**
          filters:
            - RewritePath=/lecture-service/(?<path>.*), /$\{path}
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RewritePath=/review-service/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://curady.kr"
              - "https://curady.kr"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - PATCH
              - OPTIONS
              - DELETE
springdoc:
  swagger-ui:
    urls:
      - name: user
        url: /v3/api-docs/user-service
      - name: lecture
        url: /v3/api-docs/lecture-service
      - name: review
        url: /v3/api-docs/review-service


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

---

spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  config:
    activate:
      on-profile: production

eureka:
  client:
    service-url:
      defaultZone: http://10.0.140.187:8761/eureka
